// src/SimpleStocker.Web/src/app/modules/product/pages/list-products/list-products.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-list-products',
  standalone: false,
  templateUrl: './list-products.component.html',
  styleUrl: './list-products.component.css'
})
export class ListProductsComponent {

}

<div>
  <div class="table-container">
    <div class="input-search-table">
      <input
        type="text"
        class="custom-filter-input"
        style="padding: 10px"
        placeholder="Filtrar produtos..."
        [(ngModel)]="filterText"
      />
      <button class="button-search-table" (click)="onAdd()">
        Cadastrar Produto
      </button>
    </div>

    <table class="custom-table">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Descrição</th>
          <th>Estoque</th>
          <th>Unidade</th>
          <th>Preço</th>
          <th>Categoria</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let item of filteredListItens">
          <td>{{ item.name }}</td>
          <td>{{ item.description }}</td>
          <td>{{ item.quantityStock }}</td>
          <td>{{ item.unityOfMeasurement }}</td>
          <td>{{ item.price | currency : "BRL" }}</td>
          <td>{{ item.categoryName }}</td>
          <td>
            <button
              class="action-btn edit-btn"
              (click)="onEdit(item)"
              title="Editar"
            >
              <i class="fa fa-edit"></i>
            </button>
            <button
              class="action-btn delete-btn"
              (click)="onDelete(item)"
              title="Excluir"
            >
              <i class="fa fa-trash"></i>
            </button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// src/SimpleStocker.Web/src/pages/products/ListProducts.tsx
import { useEffect, useState } from 'react'
import { Product } from '../../shared/models/Product'
import { ProductService } from '../../shared/services/ProductService'
import { useNavigate } from 'react-router-dom'

const productService = new ProductService()

export default function ListProducts() {
  const [products, setProducts] = useState<Product[]>([])
  const [loading, setLoading] = useState(true)
  const navigate = useNavigate()

  useEffect(() => {
    productService
      .getAll()
      .then((res) => setProducts(res.data ?? []))
      .finally(() => setLoading(false))
  }, [])

  return (
    <div className="card shadow mb-4">
      <div className="card-header py-3">
        <h6 className="m-0 font-weight-bold text-primary">Listar Produtos</h6>
      </div>
      <div className="card-body">
        {loading ? (
          <div>Carregando...</div>
        ) : (
          <div className="table-responsive" style={{ maxHeight: 400 }}>
            <table className="table table-bordered table-hover table-sm mb-0">
              <thead className="thead-light">
                <tr>
                  <th>ID</th>
                  <th>Nome</th>
                  <th>Descrição</th>
                  <th>Estoque</th>
                  <th>Unidade</th>
                  <th>Preço</th>
                  <th>Categoria</th>
                  <th className="text-center">Ações</th>
                </tr>
              </thead>
              <tbody>
                {products.map((p) => (
                  <tr key={p.id}>
                    <td>{p.id}</td>
                    <td>{p.name}</td>
                    <td>{p.description}</td>
                    <td>{p.quantityStock}</td>
                    <td>{p.unityOfMeasurement}</td>
                    <td>
                      {p.price.toLocaleString('pt-BR', {
                        style: 'currency',
                        currency: 'BRL',
                      })}
                    </td>
                    <td>{p.categoryName}</td>
                    <td className="text-center" style={{ minWidth: 120 }}>
                      <button
                        className="btn btn-sm btn-info mr-1"
                        title="Visualizar"
                        onClick={() => navigate(`/products/view/${p.id}`)}
                      >
                        <i className="fas fa-eye"></i>
                      </button>
                      <button
                        className="btn btn-sm btn-warning mr-1"
                        title="Editar"
                        onClick={() => navigate(`/products/update/${p.id}`)}
                      >
                        <i className="fas fa-edit"></i>
                      </button>
                      <button
                        className="btn btn-sm btn-danger"
                        title="Deletar"
                        onClick={() => navigate(`/products/delete/${p.id}`)}
                      >
                        <i className="fas fa-trash"></i>
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  )
}
